baseURL: "https://human-reasoning.github.io/"
title: Laboratory for Human Reasoning
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 1
        - name: People
          url: people/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Publications
          url: publications/
          weight: 4
        - name: News
          url: news/
          weight: 5
        - name: Join
          url: join/
          weight: 6

params:
    description: "This website hosts Moritz-Maria von Igelfeld's research papers, books, course materials, data, curriculum vitae, and contact information."
    author:
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about","people","projects","publications","news","join"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Laboratory for Human Reasoning
          subtitle: "We are a üî¨ cognitive neuroscience lab dedicated to understanding the neural basis of human ü§î reasoning and üîó association. We use üß© cognitive tasks coupled with üß† neural and üëÅÔ∏è behavioral recordings to investigate phenomena like üîé logical inference and üéØ strategic planning. If you've ever wondered how the mind thinks its way through a game of ‚ôüÔ∏è chess, so do we!"
          imageUrl: "logo.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About
              url: about/
            - name: People
              url: people/
            - name: Projects
              url: projects/
            - name: Publications
              url: publications/
            - name: News
              url: news/
            - name: Join
              url: join/

    socialIcons:
        - name: Email
          url: mailto:humanreasoning.lab@gmail.com
        - name: GitHub
          url: https://github.com/human-reasoning
        - name: Twitter
          url: https://x.com/
        - name: Google Scholar
          url: https://scholar.google.com/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Laboratory for Human Reasoning"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2